

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mm
 */
public class EmployeeScreen extends javax.swing.JDialog {
    DefaultTableModel model ;
    EmployeeActions actions = new EmployeeActions();
    
    /**
     * Creates new form EmployeeScreen
     */
    public EmployeeScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel)employee_table.getModel();
        ShowEmployee();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        employee_table = new javax.swing.JTable();
        search_area = new javax.swing.JTextField();
        name_field = new javax.swing.JTextField();
        surname_field = new javax.swing.JTextField();
        department_field = new javax.swing.JTextField();
        salary_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        message_field = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        employee_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "surname", "department", "salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employee_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employee_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employee_table);
        if (employee_table.getColumnModel().getColumnCount() > 0) {
            employee_table.getColumnModel().getColumn(0).setResizable(false);
            employee_table.getColumnModel().getColumn(1).setResizable(false);
            employee_table.getColumnModel().getColumn(2).setResizable(false);
            employee_table.getColumnModel().getColumn(3).setResizable(false);
            employee_table.getColumnModel().getColumn(4).setResizable(false);
        }

        search_area.setBackground(java.awt.SystemColor.activeCaptionBorder);
        search_area.setText("Search...");
        search_area.setToolTipText("");
        search_area.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        search_area.setName(""); // NOI18N
        search_area.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                search_areaComponentAdded(evt);
            }
        });
        search_area.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_areaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                search_areaFocusLost(evt);
            }
        });
        search_area.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_areaMouseClicked(evt);
            }
        });
        search_area.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                search_areaInputMethodTextChanged(evt);
            }
        });
        search_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_areaActionPerformed(evt);
            }
        });
        search_area.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_areaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_areaKeyTyped(evt);
            }
        });

        salary_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salary_fieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Salary");

        jLabel3.setText("Surname");

        jLabel4.setText("Department");

        message_field.setForeground(new java.awt.Color(255, 0, 0));

        add_button.setText("Add ");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(0, 0, 204));
        update.setText("Update");
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        update.setPreferredSize(new java.awt.Dimension(59, 25));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(255, 51, 0));
        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(search_area)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(message_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(surname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(department_field, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salary_field, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                .addGap(0, 57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(search_area, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_field)
                    .addComponent(add_button))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(surname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(department_field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salary_field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(message_field, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void dinamicSearch (String search){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        employee_table.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter("(?i)"+search));
        
    }
    private void search_areaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_areaKeyReleased
        
        String search = search_area.getText();
        
        dinamicSearch(search);
        
        
                
    }//GEN-LAST:event_search_areaKeyReleased

    private void search_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_areaActionPerformed
            
    }//GEN-LAST:event_search_areaActionPerformed

    private void salary_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salary_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salary_fieldActionPerformed

    private void search_areaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_areaMouseClicked
        search_area.setText("");
    }//GEN-LAST:event_search_areaMouseClicked

    private void search_areaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_search_areaInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_search_areaInputMethodTextChanged

    private void search_areaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_search_areaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_search_areaComponentAdded

    private void search_areaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_areaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_search_areaKeyTyped

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
            message_field.setText("");
            
           String name = name_field.getText();
           String surname = surname_field.getText();
           String department = department_field.getText();
           int salary =  Integer.parseInt (salary_field.getText());
           
           
           actions.addEmployee(name,surname,department,salary);
           
           ShowEmployee();
           
           message_field.setText( "Personel has been added successfully...");
           
    }//GEN-LAST:event_add_buttonActionPerformed

    private void employee_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employee_tableMouseClicked
            
        int selectedRow = employee_table.getSelectedRow();
        name_field.setText(model.getValueAt(selectedRow,1).toString());
        surname_field.setText(model.getValueAt(selectedRow,2).toString());
        department_field.setText(model.getValueAt(selectedRow,3).toString());
        salary_field.setText(model.getValueAt(selectedRow,4).toString());
        
    }//GEN-LAST:event_employee_tableMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String name = name_field.getText();
        String surname = surname_field.getText();
        String department = department_field.getText();
        int salary =  Integer.parseInt (salary_field.getText());
        
        int selectedrow = employee_table.getSelectedRow();
        
        if (selectedrow == -1) {
            
            if (model.getRowCount() == 0) {
                message_field.setText("Table is empty ");
            }
            else {
                message_field.setText("Please choose a person to update..");
            }
        }
        else {
            
            
            
            
            int id = (int)model.getValueAt(selectedrow,0);
            
            
            
            actions.updateEmployee(id,name,surname,department,salary);
            
            ShowEmployee();
            
            message_field.setText("Update succes");
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        
        message_field.setText("");
       
       int selectedrow = employee_table.getSelectedRow();
       
       if (selectedrow == -1) {
           if (model.getRowCount() == 0 ) {
               message_field.setText("Table is empty");
           }
           else {
               message_field.setText("Please choose a Person to delete");
           }
      
       }
       else {
           int id = (int)model.getValueAt(selectedrow,0);
           
           actions.deleteEmployee(id);
           
           ShowEmployee();
           
           message_field.setText("Employee has been deleted successfully");
           
           search_area.setText("");
           name_field.setText("");
           surname_field.setText("");
           department_field.setText("");
           salary_field.setText("");
           
           
       }
    }//GEN-LAST:event_deleteActionPerformed

    private void search_areaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_areaFocusGained
        
        
        search_area.setText("Search...");
        
        search_area.setForeground(Color.blue);
    }//GEN-LAST:event_search_areaFocusGained

    private void search_areaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_areaFocusLost
         search_area.setText("Search...");
        
         search_area.setForeground(Color.blue);
    }//GEN-LAST:event_search_areaFocusLost

    /**
     */
    public void ShowEmployee(){
        
        model.setRowCount(0);
        
        
        ArrayList<Employee> employees = new ArrayList<Employee>();
        
        employees = actions.getEmployee();
        
        
        if (employees != null){
           
            for (Employee employee : employees){
                
                Object [] added = { employee.getId(),employee.getName(),employee.getSurname(),employee.getDepartment(),employee.getSalary()};
                
                model.addRow(added);
                        
            }
                
                
                
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmployeeScreen dialog = new EmployeeScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JButton delete;
    private javax.swing.JTextField department_field;
    private javax.swing.JTable employee_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel message_field;
    private javax.swing.JTextField name_field;
    private javax.swing.JTextField salary_field;
    private javax.swing.JTextField search_area;
    private javax.swing.JTextField surname_field;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
